package br.unipar.projetolab.views;

import br.unipar.projetolab.cellrenderer.ExameListCellRenderer;
import br.unipar.projetolab.dao.GuiaDAO;
import br.unipar.projetolab.dao.GuiaDAOImp;
import br.unipar.projetolab.models.Guia;
import br.unipar.projetolab.models.GuiaExame;
import br.unipar.projetolab.utils.EntityManagerUtil;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Dimension;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionListener;


public class ResultadoExamePanel extends javax.swing.JPanel {

    /**
     * Creates new form ResultadoExamePanel
     */
    public ResultadoExamePanel(JPanel telaSubtsPanel) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        codigoField2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        nomeField2 = new javax.swing.JTextField();
        selecionarGuiabtn2 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        medicoCodigoField2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        medicoNomeField2 = new javax.swing.JTextField();
        convenioCodigoField2 = new javax.swing.JTextField();
        convenioNomeField2 = new javax.swing.JTextField();
        exameCodigoField2 = new javax.swing.JTextField();
        exameNomeField4 = new javax.swing.JTextField();
        nascField2 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        exameNomeField5 = new javax.swing.JTextField();
        panelExame = new javax.swing.JPanel();
        panelBtnSelecionarExames = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        examesList = new javax.swing.JList<>();
        fecharBtn = new javax.swing.JButton();

        jPanel5.setBackground(new java.awt.Color(228, 228, 228));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setText("Inclusão de Exames");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image_26.png"))); // NOI18N

        jPanel6.setBackground(new java.awt.Color(228, 228, 228));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Exame", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        codigoField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codigoField2KeyPressed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Requisição*:");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Nome*:");
        jLabel24.setToolTipText("");

        nomeField2.setEditable(false);
        nomeField2.setBackground(new java.awt.Color(204, 204, 204));
        nomeField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeField2ActionPerformed(evt);
            }
        });

        selecionarGuiabtn2.setText("Pesquisar");
        selecionarGuiabtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarGuiabtn2ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Convenio:");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Material");

        medicoCodigoField2.setEditable(false);
        medicoCodigoField2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Médico");

        medicoNomeField2.setEditable(false);
        medicoNomeField2.setBackground(new java.awt.Color(204, 204, 204));
        medicoNomeField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicoNomeField2ActionPerformed(evt);
            }
        });

        convenioCodigoField2.setEditable(false);
        convenioCodigoField2.setBackground(new java.awt.Color(204, 204, 204));

        convenioNomeField2.setEditable(false);
        convenioNomeField2.setBackground(new java.awt.Color(204, 204, 204));
        convenioNomeField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convenioNomeField2ActionPerformed(evt);
            }
        });

        exameCodigoField2.setEditable(false);
        exameCodigoField2.setBackground(new java.awt.Color(204, 204, 204));

        exameNomeField4.setEditable(false);
        exameNomeField4.setBackground(new java.awt.Color(204, 204, 204));
        exameNomeField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exameNomeField4ActionPerformed(evt);
            }
        });

        nascField2.setEditable(false);
        nascField2.setBackground(new java.awt.Color(204, 204, 204));
        nascField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nascField2ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Nasc*:");
        jLabel28.setToolTipText("");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setText("Exame");

        exameNomeField5.setEditable(false);
        exameNomeField5.setBackground(new java.awt.Color(204, 204, 204));
        exameNomeField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exameNomeField5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(codigoField2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selecionarGuiabtn2))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(nomeField2, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nascField2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel29)
                            .addComponent(jLabel25))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(medicoCodigoField2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(medicoNomeField2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(convenioCodigoField2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(convenioNomeField2))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(exameCodigoField2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exameNomeField4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exameNomeField5, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(codigoField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(selecionarGuiabtn2)))
                .addGap(7, 7, 7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomeField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28)
                        .addComponent(nascField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(medicoCodigoField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(exameNomeField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(medicoNomeField2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(convenioCodigoField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(convenioNomeField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel25))
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(exameCodigoField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exameNomeField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel29))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelExame.setLayout(new java.awt.BorderLayout());

        panelBtnSelecionarExames.setLayout(new java.awt.BorderLayout());

        examesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(examesList);

        panelBtnSelecionarExames.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel22)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelBtnSelecionarExames, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelExame, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelExame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBtnSelecionarExames, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
                .addContainerGap())
        );

        fecharBtn.setBackground(new java.awt.Color(243, 255, 229));
        fecharBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao-excluir 1.png"))); // NOI18N
        fecharBtn.setText("Fechar");
        fecharBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(fecharBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fecharBtn)
                .addGap(0, 12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void codigoField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoField2KeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) { // Verifica se a tecla pressionada foi ENTER
            try {
                Long guiaId = Long.parseLong(codigoField2.getText()); // Obtém o ID digitado
                GuiaDAO guiaDAO = new GuiaDAOImp(EntityManagerUtil.getManager());
                Guia guia = guiaDAO.findById(guiaId);

                if (guia != null) {
                    carregarGuia(guia); // Carrega os dados da guia
                } else {
                    JOptionPane.showMessageDialog(this, "Guia não encontrada para o ID: " + guiaId, "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Por favor, insira um ID válido.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_codigoField2KeyPressed

    private void nomeField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeField2ActionPerformed

    private void selecionarGuiabtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarGuiabtn2ActionPerformed
        // Abre o frame de pesquisa de requisições para edição
        resetarTela();
        RequisicaoPesquisaFrame pesquisaFrame = new RequisicaoPesquisaFrame(guia -> {
            if (guia != null) {
                carregarGuia(guia); // Carrega os dados da guia selecionada no formulário
            }
        });
        pesquisaFrame.setVisible(true);
    }//GEN-LAST:event_selecionarGuiabtn2ActionPerformed

    private void medicoNomeField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicoNomeField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicoNomeField2ActionPerformed

    private void convenioNomeField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convenioNomeField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_convenioNomeField2ActionPerformed

    private void exameNomeField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exameNomeField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exameNomeField4ActionPerformed

    private void nascField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nascField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nascField2ActionPerformed

    private void exameNomeField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exameNomeField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exameNomeField5ActionPerformed

    private void fecharBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharBtnActionPerformed
        Container parent = this.getParent();
        if (parent != null) {
            parent.remove(this); // Remove o JPanel do container pai
            parent.revalidate(); // Atualiza o layout
            parent.repaint();    // Repaint para refletir as mudanças
        }
    }//GEN-LAST:event_fecharBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigoField2;
    private javax.swing.JTextField convenioCodigoField2;
    private javax.swing.JTextField convenioNomeField2;
    private javax.swing.JTextField exameCodigoField2;
    private javax.swing.JTextField exameNomeField4;
    private javax.swing.JTextField exameNomeField5;
    private javax.swing.JList<String> examesList;
    private javax.swing.JButton fecharBtn;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField medicoCodigoField2;
    private javax.swing.JTextField medicoNomeField2;
    private javax.swing.JTextField nascField2;
    private javax.swing.JTextField nomeField2;
    private javax.swing.JPanel panelBtnSelecionarExames;
    private javax.swing.JPanel panelExame;
    private javax.swing.JButton selecionarGuiabtn2;
    // End of variables declaration//GEN-END:variables

    
    
    private void carregarGuia(Guia guia) {
        resetarTela();

        // Atualiza os campos do cabeçalho
        codigoField2.setText(String.valueOf(guia.getId())); // Usar o campo correto
        nomeField2.setText(guia.getPaciente().getNome());
        nascField2.setText(guia.getPaciente().getDataNascimento().toString());
        medicoCodigoField2.setText(String.valueOf(guia.getMedico().getId()));
        medicoNomeField2.setText(guia.getMedico().getNome());
        convenioCodigoField2.setText(guia.getConvenio() != null ? String.valueOf(guia.getConvenio().getId()) : "Particular");
        convenioNomeField2.setText(guia.getConvenio() != null ? guia.getConvenio().getNome() : "Particular");

        // Exibe os exames da guia
        mostrarExames(guia.getExames());
    }
    private void mostrarExames(List<GuiaExame> exames) {
        if (exames == null || exames.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum exame encontrado.", "Informação", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // Remove Listeners existentes para evitar problemas
        for (ListSelectionListener listener : examesList.getListSelectionListeners()) {
            examesList.removeListSelectionListener(listener);
        }

        // Atualiza a lista de exames
        DefaultListModel<String> modeloLista = new DefaultListModel<>();
        examesList.setModel(modeloLista);

        for (GuiaExame guiaExame : exames) {
            String status = "Sem resultado";
            if (guiaExame.getStatus() != null && guiaExame.getStatus().equals("Incluído")) {
                status = "Incluído";
            }
            modeloLista.addElement("<html><b>" + guiaExame.getExame().getNome() + "</b><br><i>Status: " + status + "</i></html>");
        }

        examesList.setCellRenderer(new ExameListCellRenderer());

        // Adiciona Listener para ações de seleção
        examesList.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selectedIndex = examesList.getSelectedIndex();
                if (selectedIndex != -1) {
                    GuiaExame exameSelecionado = exames.get(selectedIndex);
                    mostrarDetalhesExame(exameSelecionado);

                    // Atualiza os campos do cabeçalho com os detalhes do exame
                    exameCodigoField2.setText(String.valueOf(exameSelecionado.getExame().getId()));
                    exameNomeField4.setText(exameSelecionado.getExame().getNome());
                    exameNomeField5.setText(exameSelecionado.getExame().getTipoMaterial());
                }
            }
        });

        panelBtnSelecionarExames.revalidate();
        panelBtnSelecionarExames.repaint();
    }
    
    private void mostrarDetalhesExame(GuiaExame guiaExame) {
        panelExame.removeAll(); // Limpa o painel antes de adicionar novos detalhes

        if (guiaExame == null || guiaExame.getExame() == null) {
            JOptionPane.showMessageDialog(this, "Exame inválido ou não selecionado.");
            return;
        }

        try {
            ExameCarregaPanel detalhesPanel = new ExameCarregaPanel(guiaExame.getExame(), guiaExame.getGuia(), guiaExame);
            panelExame.add(detalhesPanel, BorderLayout.CENTER);
            System.out.println("Painel de detalhes do exame adicionado.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar os detalhes do exame: " + e.getMessage());
            e.printStackTrace();
        }

        panelExame.revalidate();
        panelExame.repaint();
    }


    private void resetarTela() {
        codigoField2.setText("");
        nomeField2.setText("");
        nascField2.setText("");
        medicoCodigoField2.setText("");
        medicoNomeField2.setText("");
        convenioCodigoField2.setText("");
        convenioNomeField2.setText("");
        exameCodigoField2.setText("");
        exameNomeField4.setText("");
        exameNomeField5.setText("");

        // Limpar lista de exames
        examesList.setModel(new DefaultListModel<>());

        // Limpar painel de detalhes
        panelExame.removeAll();
        panelExame.setLayout(new BorderLayout());
        panelExame.revalidate();
        panelExame.repaint();

        panelBtnSelecionarExames.revalidate();
        panelBtnSelecionarExames.repaint();
        System.out.println("Tela resetada.");
    }





}
